[package]
name = "adventofcode2024"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ctor = "0.2.9"
once_cell = "1.20.2"
ratatui = "0.29.0"
regex = "1.11.1"
signal-hook = "0.3.17"
